# Generated by Django 5.1 on 2024-08-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('description', models.TextField(verbose_name='内容')),
                ('is_completed', models.BooleanField(default=False, verbose_name='完了')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ToDo Item',
                'verbose_name_plural': 'ToDo Items',
            },
        ),
    ]
