# Generated by Django 5.1 on 2024-08-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.SlugField(max_length=10)),
                ('task_title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('task_description', models.TextField(blank=True, default='', null=True, verbose_name='詳細')),
                ('status', models.BooleanField(default=False, verbose_name='ステータス')),
                ('is_important', models.BooleanField(default=False, verbose_name='重要度')),
                ('priority', models.SmallIntegerField(choices=[(1, 'High'), (2, 'Middle'), (3, 'Low')], verbose_name='優先度')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='期限日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完了日')),
            ],
            options={
                'verbose_name': 'ToDo Item',
                'verbose_name_plural': 'ToDo Items',
            },
        ),
    ]
